// Store the 30 fantasy-themed agile questions
export const quests = [
  "What dark beast (blocker) blocks your path today?",
  "Which enchanted artifact (feature) did you forge yesterday?",
  "What scroll of knowledge (documentation) are you scribing today?",
  "Is your party missing any supplies (resources/help) for the journey?",
  "Have you encountered any cursed ruins (legacy code) recently?",
  "What heroic deed (completed task) are you most proud of from yesterday?",
  "Are there any rogue goblins (bugs) you need assistance tracking down?",
  "What mystical portal (API/integration) are you attempting to open today?",
  "Did any of your spells (tests) backfire during the last cycle?",
  "What uncharted territory (new feature) are you exploring next?",
  "Have you discovered any hidden treasure (optimizations) in the codebase?",
  "Is there a fellow adventurer (teammate) whose aid you require?",
  "What ancient prophecy (sprint goal) are you currently fulfilling?",
  "Did you vanquish any notable foes (resolve any major tickets) yesterday?",
  "Are your potions (coffee/energy) sufficiently stocked for today's battle?",
  "Have you consulted the elder wizards (senior devs) about your current quest?",
  "What labyrinth (complex logic) are you trying to navigate today?",
  "Are there any magical wards (security fixes) you need to reinforce?",
  "What incantation (script) are you currently perfecting?",
  "Did you unearth any forgotten lore (old documentation) that proved useful?",
  "Are you forging any new alliances (cross-team collaborations) today?",
  "What beast's lair (environment/deployment) are you venturing into next?",
  "Have you mended any broken armor (fixed failing tests) recently?",
  "What scout report (code review) did you find most illuminating?",
  "Are you constructing any new strongholds (infrastructure)?",
  "Did the gods of chaos (server outages) disrupt your plans yesterday?",
  "What map (architecture diagram) are you currently drafting or following?",
  "Are there any rival factions (competing priorities) distracting you?",
  "What grand feast (celebration/demo) are you preparing for?",
  "Has your familiar (AI assistant) been helpful in your recent battles?"
];
